site_name: 无人在意的角落
site_rul: https://blog.19970704.xyz/

nav:
  - 晚安: index.md
  - hobby:
    - anime: hobby/anime.md
    - beauty: hobby/beauty.md
  - 2025: 
    - 2025/index.md
    - 9月: 2025/september.md
  


theme:
  name: material
  icon:
    logo: material/github
  features:
    #- header.autohide
    #- navigation.tabs
    #- navigation.sections
    #- navigation.expand
    - navigation.path

  palette:
    - scheme: default
      primary: teal
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  language: zh


markdown_extensions:
  - attr_list
  - footnotes
  - def_list
  - admonition
  - abbr
  - md_in_html
  - pymdownx.blocks.caption
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg